# Generated by Django 3.2.12 on 2022-03-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
