# Generated by Django 3.2.12 on 2022-03-16 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='added_by',
            field=models.ForeignKey(db_column='added_by', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_end',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_start',
            field=models.TimeField(blank=True),
        ),
    ]
